FROM ubuntu:18.04

RUN apt-get update && apt-get -y install curl libghc-postgresql-libpq-dev libghc-text-icu-dev libghc-gd-dev postgresql-client vim net-tools cabal-install locales npm gulp cpphs
RUN apt-get update && apt-get -y install imagemagick

RUN cat /etc/ImageMagick-6/policy.xml | grep -B 10000 PDF | head -n -1 > /policy.xml && echo '<policy domain="coder" rights="read|write" pattern="PDF" />' >> /policy.xml && cat /etc/ImageMagick-6/policy.xml | grep -A 10000 PDF | tail -n +2 >> /policy.xml && mv /policy.xml /etc/ImageMagick-6/policy.xml

COPY run-server /run-server
CMD /run-server
