version: '3'
services:
  fay: 
    build: .
    volumes:
      - "./shared:/app/shared"
      - "./client:/app/client"
      - "./fay-dom:/app/fay-dom"
      - "./fay-googlemaps:/app/fay-googlemaps"
      - "./fay-jquery:/app/fay-jquery"
      - "./fay-moment:/app/fay-moment"
      - "./fay-react:/app/fay-react"
