flags: {}
packages:
- '.'
extra-deps: 
- scrypt-0.5.0
- rest-types-1.14.0.1
- tuple-th-0.2.5
- rest-gen-0.17.1
- regular-0.3.4.4
- product-profunctors-0.7.1.0
- opaleye-0.5.1.1
- postgresql-simple-0.5.2.1

resolver: lts-3.13
